### ISSUE TITLE
tracking: discord gateway implementation

### ISSUE THREAD

**Issue by Jacherr** [Jacherr/assyst2#4]
Current status is still very early, mostly still working on high-level design choices etc.

- [x] Presence state creation, connection to gateway

The current gateway presence is set correctly.

- [x] Initial shard spawning and event receiving

Assyst can currently connect to the gateway and receive events.

- [x] Pipe creation and connection to `assyst-core`

This is WIP, need to most likely create a generic `pipe` structure in `assyst-common` so we can re-use the implementation other places, such as `assyst-core` to `assyst-slash-client`, `assyst-cache`, etc.

- [x] Event parsing - handling different events in separate function calls

Need different files to handle each event, along with the event object. These will be called in a separate thread for better concurrency, but will need some kind of lock or link to the pipe to send data as needed.

- [x] Event parsing - handle message create, parse message create into command object

As a message creation is received, we need to filter it properly and decide if it's interesting to us.
We handle messages for more reasons than just commands, in particular for bad translator channels, so we need to be able to also identify those. The list of bad translator channels may need to be stored in the cache.

- [x] Event parsing - handle message update, potentially invoke, edit, or delete command (per assyst-cache)

Message update is only interesting to us if it relates to a command, namely:
- If a message is edited into a command, invoke that command,
- If a message is edited to a different command, invoke the new command and edit the message response,
- If a message is edited to be something other than a command, delete the old command response.

The semantics of this are mostly the remit of `assyst-core` but the gateway still needs to be able to tell which message updates are relevant.

- [x] Event parsing - handle message delete, potentially delete command response (per assyst-cache)

Guild deletes are only relevant if a command gets deleted, currently.

- [x] Event parsing - handle guild create and filter 'real' creations (filter guild readies out from shard spawn)

When shards transition into a READY state, Discord sends a GUILD_CREATE event for every guild that shard is responsible for.
Because Assyst doesn't cache its guilds, we need to store a list of all of these IDs so that we can differentiate these initial GUILD_CREATEs that are a side-effect of the shard readying up, from genuine additions to new guilds.

- [x] Event parsing - handle guild deletion and filter guilds becoming unavailable

Guild deletions are usually only fired when Assyst is actually removed from a guild, but guilds becoming unavailable (e.g., from an outage) can also cause this event to fire.

- [x] Receive commands from pipe (command handle done, etc?)

As messages sent to the gateway process are identified, they should be documented here.

**Comment by trueharuu** [comment]
#5 seems to complete task 6 and 7, mark as done?

**Comment by Jacherr** [comment]
Since this issue was opened, the architecture of the gateway changed slightly (https://github.com/Jacherr/assyst2/blob/master/assyst-gateway/README.md) and as such the gateway implementation is in a stable state.
